// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgdR7_Z1wHKuml4bJNhPpA7cbBv9KZQxE',
    appId: '1:135170662309:web:52e96179525c9a1928d24c',
    messagingSenderId: '135170662309',
    projectId: 'zoom-clone-da73e',
    authDomain: 'zoom-clone-da73e.firebaseapp.com',
    databaseURL: 'https://zoom-clone-da73e-default-rtdb.firebaseio.com',
    storageBucket: 'zoom-clone-da73e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ1F_nmNJJ4CqaOXbhBgmLaCQlLU-MpYI',
    appId: '1:135170662309:android:215f36d171f5e87828d24c',
    messagingSenderId: '135170662309',
    projectId: 'zoom-clone-da73e',
    databaseURL: 'https://zoom-clone-da73e-default-rtdb.firebaseio.com',
    storageBucket: 'zoom-clone-da73e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzCk-kMFVijN4D0Acs6bWL20O4Z-lEAlM',
    appId: '1:135170662309:ios:e65a3514eed67c5f28d24c',
    messagingSenderId: '135170662309',
    projectId: 'zoom-clone-da73e',
    databaseURL: 'https://zoom-clone-da73e-default-rtdb.firebaseio.com',
    storageBucket: 'zoom-clone-da73e.appspot.com',
    androidClientId: '135170662309-3o3qipg8svc2kt1kg6o0l4retvbtfv20.apps.googleusercontent.com',
    iosBundleId: 'com.example.snapShopEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzCk-kMFVijN4D0Acs6bWL20O4Z-lEAlM',
    appId: '1:135170662309:ios:e65a3514eed67c5f28d24c',
    messagingSenderId: '135170662309',
    projectId: 'zoom-clone-da73e',
    databaseURL: 'https://zoom-clone-da73e-default-rtdb.firebaseio.com',
    storageBucket: 'zoom-clone-da73e.appspot.com',
    androidClientId: '135170662309-3o3qipg8svc2kt1kg6o0l4retvbtfv20.apps.googleusercontent.com',
    iosBundleId: 'com.example.snapShopEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgdR7_Z1wHKuml4bJNhPpA7cbBv9KZQxE',
    appId: '1:135170662309:web:d7f449813030b8b228d24c',
    messagingSenderId: '135170662309',
    projectId: 'zoom-clone-da73e',
    authDomain: 'zoom-clone-da73e.firebaseapp.com',
    databaseURL: 'https://zoom-clone-da73e-default-rtdb.firebaseio.com',
    storageBucket: 'zoom-clone-da73e.appspot.com',
  );
}
